### ISSUE TITLE
Primer.style homepage update: Release 1

### ISSUE THREAD

**Issue by broccolini** [primer/primer.style#152]
See https://github.com/primer/primer.style/issues/135

- [ ] #162 Update main nav to say "about" instead of team
- [ ] #162 Redirect team to About page (anchored to point in page)
- [ ] Update header content to include "made by GitHub" para
- [ ] #161 - Add new docs showcase section using current social thumbnails. This reflects the order and content I think we should use in the first ship.

![Release 1](https://user-images.githubusercontent.com/334891/60400334-5eab2f00-9b40-11e9-8858-58819a13fd86.png)
