### ISSUE TITLE
Primer Brand and Illustration Guidelines

### ISSUE THREAD

**Issue by ashygee** [primer/primer.style#91]
### What & why
As we continue to expand the Primer brand with new sites and updates, we are running into more use cases where consistent illustrations are needed to correctly represent the Primer brand.

### Known issues/things to consider
* Currently the public interprets the Primer logo to be the package Octicon, but this has not bet solidified
* Pairing illustrations to be consistent with the site illustrations but also maintaining Primer as a separate entity
* There is currently no illustration-specific documentation 
* The illustrations should be consistent proportionally as they will need to scale based on use and display size

### Who
* @ashygee will create documentation and set up a component system for the illustrations
* @broccolini to provide current guidelines and support with design feedback and reviews (@emilybrick to support with this as well?)

### Tracking
The following assets are needed or need to be updated with new style:

#### Primer.style
- [x] Homepage
  - [x] Update Hero illustration
  - [x] Update Octicons illustration
- [x] Update Team page illustration
- [x] Update News illustration

#### Sub-site hero images
- [x] Primer CSS
- [x] Update Primer Design
- [x] Update Primer Components

#### Readme Images
- [x] Update Primer.style
- [x] Primer Design
- [x] Primer Components
- [x] Primer CSS

#### Social Images
- [ ] Spectrum chat background
- [ ] Spectrum chat avatar
- [ ] Twitter background
- [ ] Twitter avatar
- [ ] Facebook
- [ ] OG images
  - [ ] Primer.style
  - [ ] Design
  - [ ] CSS
  - [ ] Components
- [x] Template for marketing social media images

#### Identity
- [x] Global Favicon (currently package icon on or GitHub mark, or none at all)
- [ ] Repo avatar (should be consistent with Twitter Avatar etc.
- [ ] Bot avatar (can have a simple differentiator like a different color)

### Related Issues and Discussions
* [Primer.style visual identity notes](https://github.com/primer/primer.style/issues/85)
* [PR: README updates #350](https://github.com/primer/components/pull/350)
* [Primer Illustrations: Style Refinement Notes](https://github.com/primer/primer.style/issues/87)
* [README Image Concepts](https://github.com/primer/primer.style/issues/90)

**Comment by ashygee** [comment]
[Template](https://www.figma.com/file/GKpAOgd1ZtMc79uLyzWj1KE6/Social-Posts) for social images started in Figma. 

Because Figma has pre-set frame sizes for various social media platforms I think we can just add to this file. I'll set up some more social images that we can drop into our posts in the future.

**Comment by ashygee** [comment]
### Homepage Illustration Update
**Original**
![site original](https://user-images.githubusercontent.com/10384315/53608445-a6608080-3b77-11e9-9374-c60dda2e8dfd.png)

**Option 1**
![site option 1](https://user-images.githubusercontent.com/10384315/53608507-dc056980-3b77-11e9-9683-8d4a77ef3733.png)

**Option 2**
![site option 2](https://user-images.githubusercontent.com/10384315/53608510-e0ca1d80-3b77-11e9-8a34-e8e2e2b23ccf.png)

**Option 3**
![site option 3](https://user-images.githubusercontent.com/10384315/53608511-e45da480-3b77-11e9-8671-e4489cec0122.png)

### Octiocons Illustration Update
**Original**
![site octicons original](https://user-images.githubusercontent.com/10384315/53608501-d576f200-3b77-11e9-8ae2-9552cd7b9acc.png)

**Update**
![site octicons](https://user-images.githubusercontent.com/10384315/53608518-efb0d000-3b77-11e9-8e12-196e5d7410ad.png)


CC @broccolini @emilybrick

**Comment by ashygee** [comment]
Favicon updates are tied to #114.

**Comment by broccolini** [comment]
Thanks for working on this @ashygee! I think I need to see the header illustration in context with the rest of the page, it's hard for me to tell what works best when it's cropped tightly since that's not how we see it in the browser—if you have this setup with the full page in Figma can you share the link, or we can jump on a call and look through it.

Octicons is almost there but I think has a few too many details that are distracting against the surrounding content, though it looks slightly closer to the content below. I think it's also due to the higher contrast of some of the elements. Perhaps we can look at this in the browser or Figma together too?

**Comment by ashygee** [comment]
Thanks for the feedback @broccolini! 

I don't have a mock with the rest of the page yet but that's something I can set up for further discussion. I'll share the link here once I have it up.

For the Octicons illustration I will remove some of the outside details and see how that feels.

**Comment by ashygee** [comment]
@broccolini I've set up a [Figma file](https://www.figma.com/file/G0oFzd3n6nbGI0qwlMKjn9fQ/homepage-illustrations?node-id=2%3A14778) with some site mocks to view the illustrations within the full page. I also went ahead and removed some of the outer decorative elements on the Octicons illustration. Looking forward to discussing with you! 😄

**Comment by ashygee** [comment]
@broccolini Avatar ideas up on [Figma](https://www.figma.com/file/goD8kTMBTcBqTRFG26UGfSg5/Primer.style-avatar?node-id=0%3A1). There are two versions of the paintbrush taken from the previous favicon exploration in #114.

<img width="100" alt="Avatar-paintbrush" src="https://user-images.githubusercontent.com/10384315/54233775-e9511b00-44ca-11e9-9606-4c4cc3675cae.png"> <img width="100" alt="Avatar-inverted" src="https://user-images.githubusercontent.com/10384315/54233774-e9511b00-44ca-11e9-9db0-026cde7b004d.png">

**Comment by broccolini** [comment]
I'm inclined to go with the first one (dark background, more detail) and see how it works in practice. I'm fully okay with being wrong and it not working, but I think best way to test this type of change is to ship it :)

**Comment by ashygee** [comment]
@broccolini Great! I'll export and we can replace and test
